# Generated by Django 3.1.1 on 2022-02-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('food_title', models.CharField(max_length=20, verbose_name='菜品名称')),
                ('food_description', models.TextField(max_length=200, verbose_name='菜品描述')),
                ('food_location', models.CharField(max_length=30, verbose_name='食堂地址')),
                ('food_num', models.IntegerField(verbose_name='菜品数量')),
                ('food_img', models.ImageField(max_length=1000, upload_to='food_images', verbose_name='菜品图片')),
                ('food_date', models.DateField(verbose_name='菜品上架日期')),
            ],
        ),
    ]
