# Generated by Django 3.1.1 on 2022-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinfo',
            name='food_status',
            field=models.BooleanField(default=True, verbose_name='菜品是否上架'),
        ),
    ]
