# Generated by Django 3.1.1 on 2022-02-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodbooking', '0002_foodinfo_food_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBooker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='菜品预定者', to='foodbooking.foodinfo')),
            ],
        ),
    ]
