# Generated by Django 4.0.2 on 2022-02-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbooking', '0003_foodbooker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodbooker',
            options={'verbose_name': '菜品预定者', 'verbose_name_plural': '菜品预定者'},
        ),
        migrations.AlterModelOptions(
            name='foodinfo',
            options={'verbose_name': '菜品信息', 'verbose_name_plural': '菜品信息'},
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
