# Generated by Django 4.0.2 on 2022-03-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbooking', '0004_alter_foodbooker_options_alter_foodinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinfo',
            name='food_price',
            field=models.IntegerField(default=10, verbose_name='菜品价格（/份）'),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='food_num',
            field=models.IntegerField(verbose_name='菜品数量（份）'),
        ),
    ]
